version: '3'
services:
  web:
    container_name : nextApp
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - "/app/node_modules"
      - "./:/app"
    ports:
      - '3000:3000'
    restart: always
